### ISSUE TITLE
Not compatible with rspec 3.2

### ISSUE THREAD

**Issue by hooptie45** [LRDesign/rspec-steps#19]
They reworked the Hooks API 

https://github.com/rspec/rspec-core/commit/9dfc6c779e1209e07e34e30226a062f9365321cd#diff-a9e37b2e1624495fe2884d4689bf9d8a

And removed the `[]` methods, which breaks this library with the following error
```
vendor/bundle/ruby/1.9.1/gems/rspec-steps-1.0.7/lib/rspec-steps/duckpunch/hooks.rb:12:in `initialize': undefined method `[]' for RSpec::Core::FilterableItemRepository::QueryOptimized:Class (NoMethodError)
	from vendor/bundle/ruby/1.9.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1537:in `new'
	from vendor/bundle/ruby/1.9.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1537:in `hooks'
	from vendor/bundle/ruby/1.9.1/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:272:in `after'
	from vendor/bundle/ruby/1.9.1/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1497:in `after'
	from vendor/bundle/ruby/1.9.1/gems/capybara-2.4.4/lib/capybara/rspec.rb:18:in `block in <top (required)>'
	from vendor/bundle/ruby/1.9.1/gems/rspec-core-3.2.2/lib/rspec/core.rb:101:in `configure'
....
```

**Comment by nyarly** [comment]
Thanks for the heads up.

**Comment by nicolas-fricke** [comment]
Are there any concrete plans on updating this gem to support RSpec 3.2? Thanks :)

**Comment by IdahoEv** [comment]
@nicolas-fricke We usually do get around to rspec upgrades.  Unfortunately they tend to be difficult because rspec-steps necessarily hooks deep into the internals of rSpec  and the rspec team has a tendency to completely refactor their internals with every release.  

So we have a hard time prioritizing this until it's a blocker for our own work.  If you want to help, though, we'd be delighted with a PR...  :-)

**Comment by nyarly** [comment]
@nicolas-fricke @hooptie45  v2.0 was a ground-up rebuild that should be more compatible with RSpec in the foreseeable future. RSpec 3.4 is supported, and the whole 3.x line should work. Please reopen here if you have problems with compatibility
